var pairs =
{
"myzyxel":{"following":1,"account":1,"fills":1}
,"following":{"terms":1,"steps":1}
,"terms":{"may":1}
,"may":{"help":1}
,"help":{"understand":1}
,"understand":{"need":1}
,"need":{"throughout":1}
,"throughout":{"chapter":1}
,"chapter":{"register":1}
,"register":{"add":1,"new":1,"screen":1}
,"add":{"new":1,"license":1,"licenses":1}
,"new":{"device\u002Flicense":1,"device":1,"license":1,"expiration":1}
,"device\u002Flicense":{"previously":1}
,"previously":{"registered":1}
,"registered":{"myzyxel":1,"successfully":1,"devices":1,"licenses":1,"new":1,"tap":1,"license":1,"service":1,"device":1,"available":1}
,"account":{"activate":1,"tap":1,"next":1,"registered":1,"first":1,"new":1}
,"activate":{"enable":1,"new":1,"license":1,"registered":1,"tap":1,"next":1,"activate":1,"licenses":1,"service":1,"already":1,"screen":1,"device":1,"note":1}
,"enable":{"license":1}
,"license":{"device":1,"status":1,"tap":1,"scan":1,"otherwise":1,"key":1,"found":1,"name":1,"registered":1,"myzyxel":1,"already":1,"following":1,"next":1,"duration":1,"want":1,"type":1,"activation":1,"(s)":1,"license":1,"expires":1,"enter":1,"home":1,"select":1,"devices":1,"add":1,"renewed":1,"new":1,"expiration":1}
,"device":{"register":1,"tap":1,"located":1,"management":1,"enter":1,"automatically":1,"found":1,"name":1,"later":1,"bottom":1,"open":1,"want":1,"information":1,"edit":1,"able":1,"license":1,"example":1,"appear":1,"screen":1,"expired":1,"select":1}
,"tap":{"device":1,"located":1,"scan":1,"next":1,"gray":1,"name":1,"register":1,"view":1,"edit":1,"save":1,"service":1,"enter":1,"activate":1,"confirm":1,"renew":1,"registered":1,"add":1,"done":1}
,"located":{"bottom":1,"upper":1}
,"bottom":{"panel":1}
,"panel":{"open":1,"device":1,"service":1}
,"open":{"device":1,"screen":1,"service":1}
,"management":{"screen":1}
,"screen":{"tap":1,"register":1,"select":1,"saying":1,"shows":1,"appears":1,"displaying":1,"displays":1,"view":1,"licenses":1,"display":1}
,"upper":{"right":1}
,"right":{"corner":1}
,"corner":{"device":1,"service":1}
,"enter":{"device\u2019s":1,"information":1,"mac":1,"vendor\u2019s":1,"manually":1,"license":1}
,"device\u2019s":{"mac":1,"information":1,"name":1}
,"mac":{"address":1}
,"address":{"serial":1,"enter":1,"with\u002Fwithout":1}
,"serial":{"number":1}
,"number":{"tap":1,"and\u002For":1,"licenses":1}
,"scan":{"code":1}
,"code":{"scan":1,"device":1,"provided":1}
,"automatically":{"enter":1,"tap":1}
,"information":{"device":1,"appears":1,"automatically":1,"modify":1,"tap":1,"screen":1,"making":1,"view":1,"license":1}
,"found":{"device\u2019s":1,"sure":1,"myzyxel":1,"license":1}
,"appears":{"screen":1,"tap":1,"view":1,"license":1}
,"select":{"tap":1,"license":1,"number":1,"service":1}
,"next":{"note":1,"(optional)":1,"service":1,"screen":1}
,"note":{"device":1,"list":1,"activated":1}
,"sure":{"entered":1}
,"entered":{"correct":1}
,"correct":{"serial":1}
,"and\u002For":{"mac":1,"soon":1}
,"with\u002Fwithout":{"colons":1}
,"colons":{"(:)":1}
,"(:)":{"(optional)":1}
,"(optional)":{"tap":1}
,"gray":{"box":1}
,"box":{"change":1}
,"change":{"device":1}
,"name":{"recommended":1,"field":1,"it\u2019s":1,"vendor":1,"details":1,"appears":1}
,"recommended":{"leave":1}
,"leave":{"field":1}
,"field":{"empty":1,"enter":1}
,"empty":{"otherwise":1}
,"otherwise":{"harder":1,"tap":1}
,"harder":{"identify":1}
,"identify":{"device":1}
,"later":{"tap":1}
,"vendor\u2019s":{"name":1,"email":1}
,"it\u2019s":{"found":1}
,"fills":{"vendor\u2019s":1}
,"email":{"vat":1}
,"vat":{"information":1}
,"saying":{"registered":1}
,"successfully":{"appears":1}
,"view":{"registered":1,"devices":1,"screen":1,"device\u2019s":1,"services":1,"standard":1,"status":1}
,"devices":{"home":1,"expired":1,"license":1,"working":1,"display":1,"registered":1,"devices":1,"warning":1,"shown":1,"contains":1,"activate":1,"marked":1}
,"home":{"screen":1}
,"shows":{"devices":1,"registered":1}
,"expired":{"and\u002For":1,"licenses":1,"license":1}
,"soon":{"expire":1}
,"expire":{"licenses":1,"tap":1}
,"licenses":{"swipe":1,"licenses":1,"soon":1,"activated":1,"view":1,"service":1,"grouped":1,"registered":1,"want":1,"duration":1,"simultaneously":1,"choose":1,"screen":1,"activate":1,"renew":1}
,"swipe":{"left":1}
,"left":{"view":1}
,"status":{"devices":1,"licenses":1,"show":1}
,"working":{"devices":1}
,"display":{"view":1,"licenses":1}
,"warning":{"icon":1}
,"icon":{"appear":1,"modify":1,"indicates":1,"screen":1}
,"appear":{"top":1,"screen":1,"means":1}
,"top":{"meaning":1}
,"meaning":{"expired":1}
,"displaying":{"device\u2019s":1}
,"modify":{"device\u2019s":1}
,"want":{"view":1,"activate":1,"renew":1}
,"displays":{"showing":1}
,"showing":{"device":1}
,"activated":{"device":1,"renew":1,"license":1}
,"edit":{"information":1,"icon":1}
,"vendor":{"information":1}
,"making":{"changes":1}
,"changes":{"tap":1}
,"save":{"register":1}
,"service":{"located":1,"management":1,"bottom":1,"(s)":1,"number":1,"activate":1,"want":1,"choose":1,"registered":1,"device":1,"check":1}
,"provided":{"purchased":1}
,"purchased":{"license":1,"two":1}
,"manually":{"enter":1}
,"key":{"license":1,"icon":1,"extend":1,"enter":1}
,"details":{"appear":1}
,"services":{"registered":1}
,"standard":{"service":1}
,"(s)":{"registered":1,"tap":1}
,"able":{"activate":1}
,"first":{"new":1}
,"already":{"registered":1}
,"steps":{"new":1}
,"grouped":{"license":1}
,"duration":{"key":1,"year":1,"years":1}
,"indicates":{"number":1}
,"choose":{"license":1,"device":1}
,"type":{"time":1}
,"time":{"single":1}
,"single":{"device":1}
,"example":{"say":1}
,"say":{"purchased":1}
,"two":{"content":1}
,"content":{"filter":1}
,"filter":{"licenses":1}
,"year":{"activate":1}
,"simultaneously":{"using":1}
,"using":{"license":1}
,"activation":{"slider":1}
,"slider":{"license":1,"choose":1}
,"years":{"list":1}
,"list":{"available":1}
,"available":{"devices":1,"licenses":1}
,"shown":{"below":1}
,"below":{"license":1}
,"confirm":{"note":1}
,"contains":{"devices":1}
,"means":{"cannot":1}
,"cannot":{"activate":1}
,"check":{"licenses":1}
,"renew":{"expired":1,"extend":1,"license":1,"scan":1,"tap":1,"once":1}
,"expires":{"purchase":1}
,"purchase":{"new":1}
,"extend":{"renew":1,"license":1}
,"marked":{"warning":1}
,"once":{"license":1}
,"renewed":{"license":1}
,"expiration":{"date":1}
,"date":{"tap":1}
,"done":{"updated":1}
,"updated":{"screen":1}
,"show":{"license":1}
}
;Search.control.loadWordPairs(pairs);
